# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: step-functions-database-restore
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  timeout: 30

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  delete:
    handler: bin/delete
    role: deleteRole
  waitDeleted:
    handler: bin/wait-deleted
    role: waitDeletedRole
  restore:
    handler: bin/restore
    role: restoreRole
  waitAvailable:
    handler: bin/wait-available
    role: waitAvailableRole
  modify:
    handler: bin/modify
    role: modifyRole
  #updateAppUserPassword:
  #  handler: bin/update-app-user-password
  #updateCname:
  #  handler: bin/update-cname

resources:
  Resources:
    deleteRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: DatabaseRestoreDeleteRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DatabaseRestoreDeletePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds:DeleteDBCluster
                    - rds:DeleteDBInstance
                  Resource: "*"
                - Effect: Deny
                  Action:
                    - rds:DeleteDBCluster
                  Resource: "arn:aws:rds:::cluster:*-production-*"
                - Effect: Deny
                  Action:
                    - rds:DeleteDBIInstance
                  Resource: "arn:aws:rds:::db:*-production-*"
    waitDeletedRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: DatabaseRestoreWaitDeletedRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DatabaseRestoreWaitDeletedPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds:DescribeDBInstances
                    - rds:DescribeDBClusters
                  Resource: "*"
    restoreRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: DatabaseRestoreRestoreRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DatabaseRestoreRestorePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds:DescribeDBClusterSnapshots
                    - rds:RestoreDBClusterFromSnapshot
                    - rds:CreateDBInstance
                  Resource: "*"
                - Effect: Deny
                  Action:
                    - rds:RestoreDBClusterFromSnapshot
                  Resource: "arn:aws:rds:::cluster:*-production-*"
                - Effect: Deny
                  Action:
                    - rds:CreateDBInstance
                  Resource: "arn:aws:rds:::db:*-production-*"
    waitAvailableRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: DatabaseRestoreWaitAvailableRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DatabaseRestoreWaitAvailablePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds:DescribeDBInstances
                    - rds:DescribeDBClusters
                  Resource: "*"
    modifyRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: DatabaseRestoreModifyRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DatabaseRestoreModifyPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds:ModifyDBCluster
                  Resource: "*"
                - Effect: Deny
                  Action:
                    - rds:ModifyDBCluster
                  Resource: "arn:aws:rds:::cluster:*-production-*"
